export const GET_PEOPLE_START = "GET_PEOPLE_START";
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";
export const GET_PEOPLE_ERROR = "GET_PEOPLE_ERROR";
export const DELETE_PEOPLE_START = "DELETE_PEOPLE_START";